version: '3.8'
services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: doanyte
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./BackEnd
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/doanyte?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"
    volumes:
      - backend_static:/app/static
    restart: unless-stopped

  frontend:
    build:
      context: ./FrontEnd
      args:
        REACT_APP_API_URL: http://localhost:8080
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  backend_static:
